import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateReport = (project, mathLogs) => {
  const doc = new jsPDF();

  // 1. The Header & Legal Metadata
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("SURVEYOS CERTIFIED ACCURACY REPORT", 14, 22);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`PROJECT NAME: ${project?.project_name || 'UNASSIGNED'}`, 14, 32);
  doc.text(`PROJECT ID: ${project?.id || 'N/A'}`, 14, 38);
  doc.text(`TIMESTAMP: ${new Date().toLocaleString()}`, 14, 44);
  
  // Fake cryptographic hash for the "CYA Moat" aesthetic
  const mockHash = `SHA-256:${crypto.randomUUID ? crypto.randomUUID() : '8f4e2a9b7c1d3e5f'}`;
  doc.text(`DIGITAL SIGNATURE: ${mockHash}`, 14, 50);

  // 2. The Data Table Architecture
  const tableColumn = ["Point ID", "Delta E", "Delta N", "Delta Z", "3D Vector", "Status"];
  const tableRows = [];

  mathLogs.forEach(log => {
    const rowData = [
      log.point_number || log.point_id || '-',
      log.delta_e ? parseFloat(log.delta_e).toFixed(3) : '-',
      log.delta_n ? parseFloat(log.delta_n).toFixed(3) : '-',
      log.delta_z ? parseFloat(log.delta_z).toFixed(3) : '-',
      log.vector3d ? parseFloat(log.vector3d).toFixed(3) : '-',
      log.status || 'PASS'
    ];
    tableRows.push(rowData);
  });

  // 3. Render the AutoTable (Vite Strict Mode Fix)
  autoTable(doc, {
    startY: 60,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 9 },
    headStyles: { fillColor: [10, 10, 10], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    didParseCell: function(data) {
      if (data.section === 'body' && data.column.index === 5) {
        if (data.cell.raw === 'REJECTED') {
          data.cell.styles.textColor = [255, 69, 58]; // System Red
          data.cell.styles.fontStyle = 'bold';
        } else {
          data.cell.styles.textColor = [50, 215, 75]; // System Green
        }
      }
    }
  });

  // 4. The Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by SurveyOS Vault Engine - Do Not Alter | Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // 5. Trigger the Download
  doc.save(`SurveyOS_Accuracy_Report_${project?.project_name || 'Export'}.pdf`);
};